name: crossdart_server
version: 0.0.1
description: Downloads a repo, crossdartize it, and uploads JSON to GCS.

dependencies:
  redstone: any
  args: '>=0.12.2'
  googleapis: any
  googleapis_auth: any
  intl: '>=0.8.6'
  logging: '>=0.9.3'
  http: '>=0.11.1'
  yaml: any
  tasks: any
